all:
	cd ../../../FxBuilds/Builds/Linux && $(MAKE)
	cd ../../../GenBuilds/Builds/Linux && $(MAKE)

clean:
	cd ../../../FxBuilds/Builds/Linux && $(MAKE) clean
	cd ../../../GenBuilds/Builds/Linux && $(MAKE) clean

strip:
	cd ../../../FxBuilds/Builds/Linux && $(MAKE) strip
	cd ../../../GenBuilds/Builds/Linux && $(MAKE) strip
