all:
	cd ../../fx/Builds/Linux && $(MAKE)
	cd ../../gen/Builds/Linux && $(MAKE)

clean:
	cd ../../fx/Builds/Linux && $(MAKE) clean
	cd ../../gen/Builds/Linux && $(MAKE) clean

strip:
	cd ../../fx/Builds/Linux && $(MAKE) strip
	cd ../../gen/Builds/Linux && $(MAKE) strip
